# Simulator rules and constants

# ----------------------------------------------------------------
sim:
    fps: 60
    yearLength: 200

# ----------------------------------------------------------------
disp:
    baseTileSize: 55
    zoomMin: 0.15
    zoomMax: 1.2
    zoomDefault: 1
    startViewX: 0
    startViewY: 0
    hueRed: 10
    hueGreen: 100
    repr:
        fertMin: 0.6
        fertMax: 1.5
        tempMin: -10
        tempMax: 30
        humdMin: 0
        humdMax: 100
        tileSat: 80
        tileLum: 40
    style: # Style canvas
        percW: 80 # Vertical view: Width [Percentage]
        percH: 80 # Horizontal view: Height [Percentage]
        borderX: 2 # Canvas border
        borderY: 2 # Canvas border
        hiddenBarSize: 15
    season: [
        Summer, Autumn, Winter, Spring]

# ----------------------------------------------------------------
map:
    widthMin: 30
    widthMax: 30
    heightMin: 30
    heightMax: 30

# ----------------------------------------------------------------
food:
    baseEff: 1
    # Defining food kinds
    kindsAmount: 100
    kindEffMin: 0.9
    kindEffMax: 1.3
    kindTempPrefMin: 10
    kindTempPrefMax: 20
    kindTempTolrMin: 0.5
    kindTempTolrMax: 1.2
    kindHumdPrefMin: 40
    kindHumdPrefMax: 80
    kindHumdTolrMin: 1.4
    kindHumdTolrMax: 2

# ----------------------------------------------------------------
tile:
    # Global
    erosionPerThousand: 0.0005 # 0.0005 -> 20 yrs
    baseLootRecovery: 0.0005 # 0.0005 -> 2 yrs
    # Tile - specific randomized attributes
    baseFertilityMin: 0.7
    baseFertilityMax: 1.3
    baseHumdMin: -5
    baseHumdMax: 5
    lootRecoveryFactorMin: 0.8
    lootRecoveryFactorMax: 1.2

# ----------------------------------------------------------------
climate:
    baseTemp: 8
    baseGhg: 1
    baseHumd: 50
    # Amplitudes
    tempSeasonAmp: 20
    humdSeasonAmp: 35
    tempLocalAmp: 2
    humdLocalAmp: 5
    localAmpIncrease: 0.3
    event:
        globalDrought:
            minInterval: 2000 # 2000 -> 20 yrs
            chance: 0.005
            delayMin: 5
            delayMax: 80
