# Simulator rules and constants

# ----------------------------------------------------------------
sim:
    fps: 30 # Prefferably a multiple of changeSpeedStep
    yearLength: 400
    maxAllowedFps: 600
    changeSpeedStep: 10

# ----------------------------------------------------------------
disp:
    defaultBarPos: v
    toggleBarAtWidth: 800
    baseTileSize: 55
    zoomMin: 0.15
    zoomMax: 1.2
    zoomDefault: 1
    startViewX: 0
    startViewY: 0
    hueRed: 0
    hueGreen: 190
    repr:
        fertMin: 0.6
        fertMax: 1.5
        tempMin: -10
        tempMax: 30
        humdMin: 0
        humdMax: 100
        tileSat: 80
        tileLum: 40
    style: # Style canvas
        percW: 80 # Vertical view: Width [Percentage]
        percH: 70 # Horizontal view: Height [Percentage]
        borderX: 2 # Canvas border
        borderY: 2 # Canvas border
        hiddenBarSize: 15
    season: [
        Summer, Autumn, Winter, Spring]

# ----------------------------------------------------------------
map:
    widthMin: 50
    widthMax: 50
    heightMin: 50
    heightMax: 50

# ----------------------------------------------------------------
food:
    baseEff: 1
    foodKindNoise: 8
    # Defining food kinds
    kindsAmount: 100
    kindEffMin: 0.9
    kindEffMax: 1.3
    # Temp: Preferred / Tolerance
    kindTempPrefMin: 10
    kindTempPrefMax: 20
    kindTempTolrMin: 3
    kindTempTolrMax: 5
    # Humidity: Preferred / Tolerance
    kindHumdPrefMin: 40
    kindHumdPrefMax: 80
    kindHumdTolrMin: 7
    kindHumdTolrMax: 26
    specific:
        startStrength: 50
        maxStrength: 100
        moveStrength: 70 # Strength required to duplicate

# ----------------------------------------------------------------
tile:
    erosionPerThousand: 0.0005 # 0.0005 -> 20 yrs
    baseLootRecovery: 0.0005 # 0.0005 -> 2 yrs
    # Fertility noise
    fertNoise: 22
    baseFertilityMin: 0.7
    baseFertilityMax: 1.3

# ----------------------------------------------------------------
climate:
    # Temperature
    baseTemp: 1
    lngTempFactor: 20
    tempSeasonAmp: 10
    tempLocalAmp: 8
    # Humidity
    baseHumd: 30
    latHumdFactor: 40
    humdSeasonAmp: 20
    humdLocalAmp: 21
    # Greenhouse effect
    baseGreenhouse: 1
    # Clouds
    climNoise: 17
    maxCloudVel: 0.03
    maxCloudAccl: 0.002
    negShiftFactor: 0.85
    # Events
    event:
        globalDrought:
            minInterval: 2000 # 2000 -> 20 yrs
            chance: 0.005
            delayMin: 5
            delayMax: 80
