# Simulator rules and constants

# ----------------------------------------------------------------
sim:
    fps:
        max: 240
        default: 240
        step: 10
    yearLength: 365

# ----------------------------------------------------------------
disp:
    zoom:
        max: 1.2
        min: 0.15
        default: 0.27
    elems: # Size of elements in x1 zoom
        tile: 55
    range:
        fert:
            max: 1.2
            min: 0.8
        temp:
            max: 30
            min: -10
        humd:
            max: 100
            min: 0
        fruit:
            max: 50
            min: 0
        strength:
            max: 100
            min: 0
    color:
        sat: 80
        lum:
            max: 55
            min: 10
            default: 40
            placeholder: 30
        hue:
            max: 190
            min: 0
    canvas:
        percW: 80 # Vertical view: Width [Percentage]
        percH: 70 # Horizontal view: Height [Percentage]
        borderX: 2 # Canvas border
        borderY: 2 # Canvas border
    ui:
        toggleBarAtWidth: 800
        hiddenBarSize: 15
    season: [
        Summer, Autumn, Winter, Spring]

# ----------------------------------------------------------------
map:
    widthMin: 54
    widthMax: 54
    heightMin: 76
    heightMax: 76

# ----------------------------------------------------------------
food:
    strength:
        max: 100
        start: 30
    growth:
        temp:
            scale: 0.5
            efficiency: 10
            range:
                max: 1.35
                min: -0.95
        humd:
            scale: 0.3
            efficiency: 15
            range:
                max: 1.2
                min: -1
        base: 1.4
        loseMultiplier: 1.5
    # Cloning
    clone:
        minStrength: 70
        minAge: 0.3
        minNeighbours: 1
    trait:
        efficiency:
            base: 1
            baseAmp: 0.1
            mutateAmp: 0.02
            noiseScale: 12
        tempPref:
            base: 13
            baseAmp: 17
            mutateAmp: 1.5
            noiseScale: 10
        humdPref:
            base: 50
            baseAmp: 45
            mutateAmp: 2
            noiseScale: 10
        fruitType:
            base: 25
            baseAmp: 25
            mutateAmp: 0.25
            noiseScale: 8

# ----------------------------------------------------------------
tile:
    fertility:
        base: 1
        baseAmp: 0.3
        noiseScale: 22
    ownedFood:
        diedCooldown: 0.334 #[years]
        newChance: 0.9 #[%]

# ----------------------------------------------------------------
climate:
    temp:
        base: 14
        seasonAmp: 13
        longitudeAmp: 25
        localAmp: 9
    humd:
        base: 50
        seasonAmp: 25
        latitudeAmp: 45
        localAmp: 25
    greenhouse:
        base: 1
    cloud:
        noiseScale: 17
        vel:
            max: 0.03
            step: 0.002
            backwdFactor: 0.85
    # Events
    event:
        globalDrought:
            minInterval: 2000 # 2000 -> 20 yrs
            chance: 0.005
            delayMin: 5
            delayMax: 80

# ----------------------------------------------------------------
tribe:
    addIfLessThan: 30
    startAmount: 50
    pops: # Population
        start: 100
        minTile: 40
    food:
        startAcc: 20
        incomeScale: 20
        foodPerPop: 0.001
