# Simulator rules and constants

# ----------------------------------------------------------------
sim:
    fps: 60
    yearLength: 200

# ----------------------------------------------------------------
disp:
    defaultBarPos: v
    toggleBarAtWidth: 800
    baseTileSize: 55
    zoomMin: 0.15
    zoomMax: 1.2
    zoomDefault: 1
    startViewX: 0
    startViewY: 0
    hueRed: 0
    hueGreen: 190
    repr:
        fertMin: 0.6
        fertMax: 1.5
        tempMin: -10
        tempMax: 30
        humdMin: 0
        humdMax: 100
        tileSat: 80
        tileLum: 40
    style: # Style canvas
        percW: 80 # Vertical view: Width [Percentage]
        percH: 70 # Horizontal view: Height [Percentage]
        borderX: 2 # Canvas border
        borderY: 2 # Canvas border
        hiddenBarSize: 15
    season: [
        Summer, Autumn, Winter, Spring]

# ----------------------------------------------------------------
map:
    widthMin: 30
    widthMax: 30
    heightMin: 30
    heightMax: 30

# ----------------------------------------------------------------
food:
    baseEff: 1
    # Defining food kinds
    kindsAmount: 100
    kindEffMin: 0.9
    kindEffMax: 1.3
    kindTempPrefMin: 10
    kindTempPrefMax: 20
    kindTempTolrMin: 0.5
    kindTempTolrMax: 1.2
    kindHumdPrefMin: 40
    kindHumdPrefMax: 80
    kindHumdTolrMin: 1.4
    kindHumdTolrMax: 2

# ----------------------------------------------------------------
tile:
    # Global
    erosionPerThousand: 0.0005 # 0.0005 -> 20 yrs
    baseLootRecovery: 0.0005 # 0.0005 -> 2 yrs
    # Tile - specific randomized attributes
    baseFertilityMin: 0.7
    baseFertilityMax: 1.3
    fertilityNoiseStep: 0.15
    baseHumdMin: -15
    baseHumdMax: 15

# ----------------------------------------------------------------
climate:
    baseTemp: 1
    baseGhg: 1
    baseHumd: 30
    # Perlin Noise
    perlinClimate: 17
    perlinFert: 22
    maxDvtShiftStep: 0.002
    maxDvtVel: 0.01
    negShiftFactor: 0.85
    # Location - depended
    lngTempFactor: 20
    latHumdFactor: 40
    # Amplitudes
    tempSeasonAmp: 10
    humdSeasonAmp: 20
    tempLocalAmp: 8
    humdLocalAmp: 21
    event:
        globalDrought:
            minInterval: 2000 # 2000 -> 20 yrs
            chance: 0.005
            delayMin: 5
            delayMax: 80
