# Simulator rules and constants

# ----------------------------------------------------------------
sim:
    yearLength: 365 # [ticks]
    fps:
        max: 240
        default: 40
        step: 10

# ----------------------------------------------------------------
disp:
    zoom:
        max: 2
        min: 0.3
        default: 1
    elems: # Size of elements in x1 zoom
        tile: 18
    range: # Values mapped to colors
        fert:
            max: 1.2
            min: 0.8
        temp:
            max: 30
            min: -10
        humd:
            max: 100
            min: 0
        fruit:
            max: 40
            min: 10
        strength:
            max: 100
            min: 0
    color: # Color definitions
        sat:
            default: 80
            foodTribeScale: 4.5
        lum:
            max: 55
            min: 10
            default: 40
            placeholder: 30
            foodTribe:
                max: 40
                min: 5
        hue:
            max: 190
            min: 0
    season: [
        Summer, Autumn, Winter, Spring]

# ----------------------------------------------------------------
map:
    width: 48
    height: 48

# ----------------------------------------------------------------
food:
    strength:
        max: 100
        start: 30
    growth:
        base: 1.4
        loseMultiplier: 1.5
        temp:
            scale: 0.5
            efficiency: 10
            range:
                max: 1.35
                min: -0.95
        humd:
            scale: 0.3
            efficiency: 15
            range:
                max: 1.2
                min: -1
    clone:
        minStrength: 70
        minAge: 0.3
        minNeighbours: 1
    trait:
        efficiency:
            base: 1
            baseAmp: 0.1
            mutateAmp: 0.02
            noiseScale: 12
        tempPref:
            base: 13
            baseAmp: 17
            mutateAmp: 1.5
            noiseScale: 10
        humdPref:
            base: 50
            baseAmp: 45
            mutateAmp: 2
            noiseScale: 10
        fruitType:
            # NOTE: base and baseAmp must sum to what is
                # in food.fruitTypes
            base: 25
            baseAmp: 25
            mutateAmp: 0.25
            noiseScale: 8

# ----------------------------------------------------------------
tile:
    fertility:
        base: 1
        baseAmp: 0.3
        noiseScale: 22
    ownedFood:
        diedCooldown: 0.334 # [years]
        newChance: 0.9 # [%]

# ----------------------------------------------------------------
climate:
    temp:
        base: 14
        seasonAmp: 13
        longitudeAmp: 25
        localAmp: 9
    humd:
        base: 50
        seasonAmp: 25
        latitudeAmp: 45
        localAmp: 25
    greenhouse:
        base: 1
    cloud:
        noiseScale: 17
        vel:
            max: 0.03
            step: 0.002
            backwdFactor: 0.85
    # Events
    event: # Events are not implemented yet
        globalDrought:
            minInterval: 2000 # 2000 -> 20 yrs
            chance: 0.005
            delayMin: 5
            delayMax: 80

# ----------------------------------------------------------------
tribe:
    amount: # Amount of tribes in simulation
        start: 80
        min: 50
    pops: # Population
        start: 75
        max: 200 # No more than this can live on a tile
    eco: # Food Economy
        incomeMultiplier: 0.1
        fruitEfficiency: 7
        shortageSeverityFactor: 0.6
        foodPerPop: 0.03
        capacity:
            base: 10
            perPop: 0.8
    migrate:
        cooldown:
            base: 0.1 # [years]
            amp: 0.02 # [years]
        cost: 0.01 # [food] per pop
