# Simulator rules and constants

# ----------------------------------------------------------------
sim:
    fps:
        max: 240
        default: 30
        step: 10
    yearLength: 365

# ----------------------------------------------------------------
disp:
    zoom:
        max: 1.2
        min: 0.15
        default: 1
    elems: # Size of elements in x1 zoom
        tile: 55
    range:
        fert:
            max: 1.5
            min: 0.6
        temp:
            max: 30
            min: -10
        humd:
            max: 100
            min: 0
        strength:
            max: 100
            min: 0
    color:
        sat: 80
        lum:
            max: 55
            min: 10
            default: 40
            placeholder: 30
        hue:
            max: 190
            min: 0
    canvas:
        percW: 80 # Vertical view: Width [Percentage]
        percH: 70 # Horizontal view: Height [Percentage]
        borderX: 2 # Canvas border
        borderY: 2 # Canvas border
    ui:
        toggleBarAtWidth: 800
        hiddenBarSize: 15
    season: [
        Summer, Autumn, Winter, Spring]

# ----------------------------------------------------------------
map:
    widthMin: 50
    widthMax: 50
    heightMin: 50
    heightMax: 50

# ----------------------------------------------------------------
food:
    strength:
        max: 100
        start: 30
    growth:
        base: 0.02
        loseMultiplier: 10
    # Efficiency constants and importance factors
    tempEfficiency: 10
    tempImportance: 1
    humdEfficiency: 30
    humdImportance: 0.4
    # Cloning
    clone:
        minStrength: 70
        minAge: 0.3
        minNeighbours: 1
    trait:
        efficiency:
            base: 1
            baseAmp: 0.1
            mutateAmp: 0.02
            noiseScale: 12
        tempPref:
            base: 13
            baseAmp: 17
            mutateAmp: 1.5
            noiseScale: 10
        humdPref:
            base: 45
            baseAmp: 35
            mutateAmp: 2
            noiseScale: 10
        fruitType:
            base: 10
            baseAmp: 10
            mutateAmp: 0.25
            noiseScale: 8

# ----------------------------------------------------------------
tile:
    fertility:
        base: 1
        baseAmp: 0.3
        noiseScale: 22
    ownedFood:
        diedCooldown: 0.67 #[years]
        newChance: 0.9 #[%]

# ----------------------------------------------------------------
climate:
    temp:
        base: 14
        seasonAmp: 13
        longitudeAmp: 25
        localAmp: 9
    humd:
        base: 50
        seasonAmp: 25
        latitudeAmp: 45
        localAmp: 25
    greenhouse:
        base: 1
    cloud:
        noiseScale: 17
        vel:
            max: 0.03
            step: 0.002
            backwdFactor: 0.85
    # Events
    event:
        globalDrought:
            minInterval: 2000 # 2000 -> 20 yrs
            chance: 0.005
            delayMin: 5
            delayMax: 80
