# Simulator rules and constants

# ----------------------------------------------------------------
sim:
    fps: 30 # Prefferably a multiple of changeSpeedStep
    yearLength: 365
    maxAllowedFps: 240
    changeSpeedStep: 10

# ----------------------------------------------------------------
disp:
    defaultBarPos: v
    toggleBarAtWidth: 800
    baseTileSize: 55
    zoomMin: 0.15
    zoomMax: 1.2
    zoomDefault: 1
    startViewX: 0
    startViewY: 0
    hueRed: 0
    hueGreen: 190
    repr:
        fertMin: 0.6
        fertMax: 1.5
        tempMin: -10
        tempMax: 30
        humdMin: 0
        humdMax: 100
        tileSat: 80
        tileLum: 40
    style: # Style canvas
        percW: 80 # Vertical view: Width [Percentage]
        percH: 70 # Horizontal view: Height [Percentage]
        borderX: 2 # Canvas border
        borderY: 2 # Canvas border
        hiddenBarSize: 15
    season: [
        Summer, Autumn, Winter, Spring]

# ----------------------------------------------------------------
map:
    widthMin: 50
    widthMax: 50
    heightMin: 50
    heightMax: 50

# ----------------------------------------------------------------
food:
    # Strength and Growth
    baseGrowth: 0.2
    startStrength: 30
    maxStrength: 100
    loseMultiplier: 1.4 # How much times faster food loses
        # strength than gains
    # Efficiency constants (At what difference growth falls to 0)
    tempEfficiency: 10.3
    humdEfficiency: 30
    # Growth factors importance
    tempImportance: 1
    humdImportance: 0.4
    # Cloning
    cloneStrength: 70
    cloneMinAge: 0.3 # multiplied by sim.yearLength
    minCloneNeighbours: 1 # Min amount of alive neighbours to
        # create food
    trait:
        efficiency:
            base: 1
            strengthAmp: 0.1
            mutateAmp: 0.02
            noiseScale: 12
        tempPref:
            base: 13
            strengthAmp: 17
            mutateAmp: 1.5
            noiseScale: 10
        humdPref:
            base: 45
            strengthAmp: 35
            mutateAmp: 2
            noiseScale: 10

# ----------------------------------------------------------------
tile:
    erosionPerThousand: 0.0005 # 0.0005 -> 20 yrs
    baseLootRecovery: 0.0005 # 0.0005 -> 2 yrs
    # Fertility noise
    fertNoise: 22
    baseFertilityMin: 0.7
    baseFertilityMax: 1.3
    # How long before tile can get another food after prev died
        # multiplied by sim.yearLength
    foodDiedCooldown: 0.67
    # Chance of tile getting new food
    foodNewChance: 1

# ----------------------------------------------------------------
climate:
    # Temperature
    baseTemp: 14
    lngTempFactor: 25
    tempSeasonAmp: 13 # x2
    tempLocalAmp: 9
    # Humidity
    baseHumd: 50
    latHumdFactor: 45
    humdSeasonAmp: 25 # x2
    humdLocalAmp: 25
    # Greenhouse effect
    baseGreenhouse: 1
    # Clouds
    climNoise: 17
    maxCloudVel: 0.03
    maxCloudAccl: 0.002
    negShiftFactor: 0.85
    # Events
    event:
        globalDrought:
            minInterval: 2000 # 2000 -> 20 yrs
            chance: 0.005
            delayMin: 5
            delayMax: 80
